#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using HuatongApply.Data;

namespace HuatongApply.Data
{
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.Diagnostics.DebuggerDisplay("DetailId: {DetailId}")]
    public partial class Applydetail : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "5.0.0.0")]
        static Applydetail()
        {
            AddSharedRules();
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public Applydetail()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        protected override void Initialize()
        {
            OnCreated();
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Int32 _detailId;
        
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Int32 DetailId
        {
            get { return _detailId; }
            set
            {
                OnDetailIdChanging(value, _detailId);
                SendPropertyChanging("DetailId");
                _detailId = value;
                SendPropertyChanged("DetailId");
                OnDetailIdChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Int32? _count;
        
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Int32? Count
        {
            get { return _count; }
            set
            {
                OnCountChanging(value, _count);
                SendPropertyChanging("Count");
                _count = value;
                SendPropertyChanged("Count");
                OnCountChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Double? _price;
        
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.Double? Price
        {
            get { return _price; }
            set
            {
                OnPriceChanging(value, _price);
                SendPropertyChanging("Price");
                _price = value;
                SendPropertyChanged("Price");
                OnPriceChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.DateTime? _createdOn;
        
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.DateTime? CreatedOn
        {
            get { return _createdOn; }
            set
            {
                OnCreatedOnChanging(value, _createdOn);
                SendPropertyChanging("CreatedOn");
                _createdOn = value;
                SendPropertyChanged("CreatedOn");
                OnCreatedOnChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _createdBy;
        
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String CreatedBy
        {
            get { return _createdBy; }
            set
            {
                OnCreatedByChanging(value, _createdBy);
                SendPropertyChanging("CreatedBy");
                _createdBy = value;
                SendPropertyChanged("CreatedBy");
                OnCreatedByChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.DateTime? _modifiedOn;
        
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.DateTime? ModifiedOn
        {
            get { return _modifiedOn; }
            set
            {
                OnModifiedOnChanging(value, _modifiedOn);
                SendPropertyChanging("ModifiedOn");
                _modifiedOn = value;
                SendPropertyChanged("ModifiedOn");
                OnModifiedOnChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.String _modifiedBy;
        
        [System.Runtime.Serialization.DataMember(Order = 7)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual System.String ModifiedBy
        {
            get { return _modifiedBy; }
            set
            {
                OnModifiedByChanging(value, _modifiedBy);
                SendPropertyChanging("ModifiedBy");
                _modifiedBy = value;
                SendPropertyChanged("ModifiedBy");
                OnModifiedByChanged(value);
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private Applyrecord _applyrecord;
        
        [System.Runtime.Serialization.DataMember(Order = 8, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual Applyrecord Applyrecord
        {
            get { return _applyrecord; }
            set
            {
                OnApplyrecordChanging(value, _applyrecord);
                SendPropertyChanging("Applyrecord");
                _applyrecord = value;
                SendPropertyChanged("Applyrecord");
                OnApplyrecordChanged(value);
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private Applyitem _applyitem;
        
        [System.Runtime.Serialization.DataMember(Order = 9, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual Applyitem Applyitem
        {
            get { return _applyitem; }
            set
            {
                OnApplyitemChanging(value, _applyitem);
                SendPropertyChanging("Applyitem");
                _applyitem = value;
                SendPropertyChanged("Applyitem");
                OnApplyitemChanged(value);
            }
        }
        
        #endregion
        
        #region Extensibility Method
        
        static partial void AddSharedRules();
        
        partial void OnCreated();
        
        partial void OnDetailIdChanging(System.Int32 newValue, System.Int32 oldValue);
        
        partial void OnDetailIdChanged(System.Int32 value);
        
        partial void OnCountChanging(System.Int32? newValue, System.Int32? oldValue);
        
        partial void OnCountChanged(System.Int32? value);
        
        partial void OnPriceChanging(System.Double? newValue, System.Double? oldValue);
        
        partial void OnPriceChanged(System.Double? value);
        
        partial void OnCreatedOnChanging(System.DateTime? newValue, System.DateTime? oldValue);
        
        partial void OnCreatedOnChanged(System.DateTime? value);
        
        partial void OnCreatedByChanging(System.String newValue, System.String oldValue);
        
        partial void OnCreatedByChanged(System.String value);
        
        partial void OnModifiedOnChanging(System.DateTime? newValue, System.DateTime? oldValue);
        
        partial void OnModifiedOnChanged(System.DateTime? value);
        
        partial void OnModifiedByChanging(System.String newValue, System.String oldValue);
        
        partial void OnModifiedByChanged(System.String value);
        
        
        partial void OnApplyrecordChanging(Applyrecord newValue, Applyrecord oldValue);
        
        partial void OnApplyrecordChanged(Applyrecord value);
        
        partial void OnApplyitemChanging(Applyitem newValue, Applyitem oldValue);
        
        partial void OnApplyitemChanged(Applyitem value);
        
        #endregion
        
        #region Clone
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public virtual Applydetail Clone()
        {
            return (Applydetail)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML String.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static Applydetail FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(Applydetail));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as Applydetail;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static Applydetail FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(Applydetail));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as Applydetail;
            }
        }
        
        #endregion
    }
}

#pragma warning restore 1591
#pragma warning restore 0414

