#pragma warning disable 1591
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Text;
using NHibernate;
using NHibernate.Cfg;
using CodeSmith.Data.Linq;
using CodeSmith.Data.NHibernate;
using Configuration = NHibernate.Cfg.Configuration;
using Environment = NHibernate.Cfg.Environment;
using HuatongApply.Data;

namespace HuatongApply.Data
{
    public partial class HuatongApplyContext : NHibernateDataContext
    {
        #region Session Implementation

        private static object _sessionFactoryLock = new object();

        private static ISessionFactory _sessionFactory = null;

        private ISessionFactory SessionFactory
        {
            get
            {
                lock (_sessionFactoryLock)
                    if (_sessionFactory == null)
						_sessionFactory = CreateSessionFactory("HuatongApply",
                            "HuatongApply.Data",
                            "NHibernate.Dialect.MsSql2005Dialect",
                            "NHibernate.Driver.SqlClientDriver");

                return _sessionFactory;
            }
        }

        protected override ISession CreateSession()
        {
            return SessionFactory.OpenSession();
        }
        
        protected override IStatelessSession CreateStatelessSession()
        {
            return SessionFactory.OpenStatelessSession();
        }
        
        #endregion
        
        #region Tables
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<HuatongApply.Data.Applydetail> _applydetail;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<HuatongApply.Data.Applydetail> Applydetail
        {
            get
            {
                if (_applydetail == null)
                    _applydetail = new Table<HuatongApply.Data.Applydetail>(this);
                return _applydetail;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<HuatongApply.Data.Applyitem> _applyitem;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<HuatongApply.Data.Applyitem> Applyitem
        {
            get
            {
                if (_applyitem == null)
                    _applyitem = new Table<HuatongApply.Data.Applyitem>(this);
                return _applyitem;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<HuatongApply.Data.Applyrecord> _applyrecord;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<HuatongApply.Data.Applyrecord> Applyrecord
        {
            get
            {
                if (_applyrecord == null)
                    _applyrecord = new Table<HuatongApply.Data.Applyrecord>(this);
                return _applyrecord;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private ITable<HuatongApply.Data.Fundflow> _fundflow;
        
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public ITable<HuatongApply.Data.Fundflow> Fundflow
        {
            get
            {
                if (_fundflow == null)
                    _fundflow = new Table<HuatongApply.Data.Fundflow>(this);
                return _fundflow;
            }
        }
        
        #endregion
        
        #region Views
        
        #endregion
        
        #region Functions
        
        #endregion
    }
}

